- name: Remote Minecraft Server Deployer
  hosts: 34.220.9.99
  become: true
  vars:
    ansible_ssh_private_key_file: C:\Users\jflesch\Downloads\dc_key.pem
  tasks:
    - name: Transfer the script
      copy: src=deploy_minecraft_v1.0.bash dest=/home/ubuntu mode=0777

    - name: Execute the script
      command: sh /home/ubuntu/deploy_minecraft_v1.0.bash